PROJETO=aula
#gera um novo projeto e instala bibliotecas
npx -y create-docusaurus@latest ${PROJETO} classic --typescript

#entra no diretorio onde o projeto foi criado
cd ${PROJETO}

npm install

npx docusaurus start --host 0.0.0.0
